-- Additional starter questions: brainstorm + estimation (~50).

INSERT INTO public.questions (text, species, tags, upvotes, difficulty, status)
VALUES
  ('What everyday problem deserves a radically simple app?', 'brainstorm', ARRAY['ideas', 'product'], 0, 1, 'published'),
  ('Name one policy that would reduce loneliness without surveillance.', 'brainstorm', ARRAY['discourse', 'society'], 0, 2, 'published'),
  ('What would make online debates feel more curious and less performative?', 'brainstorm', ARRAY['discourse', 'internet'], 0, 2, 'published'),
  ('Suggest a question schools should ask students weekly.', 'brainstorm', ARRAY['education', 'ideas'], 0, 1, 'published'),
  ('What habit helps you update your beliefs faster?', 'brainstorm', ARRAY['thinking', 'habits'], 0, 1, 'published'),
  ('One invention from sci-fi you wish existed — and why?', 'brainstorm', ARRAY['ideas', 'culture'], 0, 1, 'published'),
  ('How could cities encourage more cross-class conversation?', 'brainstorm', ARRAY['discourse', 'cities'], 0, 2, 'published'),
  ('What metric should replace GDP in public debate?', 'brainstorm', ARRAY['economics', 'discourse'], 0, 3, 'published'),
  ('Name a boring institution that secretly shapes how we think.', 'brainstorm', ARRAY['society', 'thinking'], 0, 2, 'published'),
  ('What would a “healthy” social feed optimize for?', 'brainstorm', ARRAY['internet', 'discourse'], 0, 2, 'published'),
  ('Suggest one ritual for productive disagreement at work.', 'brainstorm', ARRAY['work', 'discourse'], 0, 1, 'published'),
  ('What question would reveal whether someone is open-minded?', 'brainstorm', ARRAY['thinking', 'social'], 0, 2, 'published'),
  ('One small design change that would improve democracy online.', 'brainstorm', ARRAY['discourse', 'design'], 0, 2, 'published'),
  ('What topic do smart people disagree about for good reasons?', 'brainstorm', ARRAY['discourse', 'thinking'], 0, 2, 'published'),
  ('How would you explain curiosity to an alien?', 'brainstorm', ARRAY['ideas', 'philosophy'], 0, 1, 'published'),
  ('Name a trade-off society avoids talking about honestly.', 'brainstorm', ARRAY['discourse', 'society'], 0, 3, 'published'),
  ('What would you put on a “thinking skills” curriculum?', 'brainstorm', ARRAY['education', 'thinking'], 0, 2, 'published'),
  ('Suggest a better way to score ideas in a brainstorm.', 'brainstorm', ARRAY['ideas', 'work'], 0, 1, 'published'),
  ('What makes a question worth asking in public?', 'brainstorm', ARRAY['meta', 'discourse'], 0, 2, 'published'),
  ('One feature every knowledge app gets wrong.', 'brainstorm', ARRAY['product', 'internet'], 0, 2, 'published'),
  ('How many hours does the average person spend on their phone daily?', 'estimation', ARRAY['technology', 'habits'], 0, 2, 'published'),
  ('What percentage of people believe they are above-average drivers?', 'estimation', ARRAY['psychology', 'thinking'], 0, 2, 'published'),
  ('How many books does the average adult read per year?', 'estimation', ARRAY['culture', 'habits'], 0, 2, 'published'),
  ('What share of news headlines would change your mind if you read the full article?', 'estimation', ARRAY['media', 'discourse'], 0, 3, 'published'),
  ('How many close friends does the average person have?', 'estimation', ARRAY['social', 'psychology'], 0, 2, 'published'),
  ('What percent of workplace meetings could be an email?', 'estimation', ARRAY['work', 'culture'], 0, 2, 'published'),
  ('How many countries have more than 50 million people?', 'estimation', ARRAY['geography', 'facts'], 0, 2, 'published'),
  ('What fraction of scientific studies replicate on first attempt?', 'estimation', ARRAY['science', 'thinking'], 0, 3, 'published'),
  ('How many languages are spoken worldwide?', 'estimation', ARRAY['culture', 'facts'], 0, 2, 'published'),
  ('What percentage of couples met online in the last decade?', 'estimation', ARRAY['social', 'internet'], 0, 2, 'published'),
  ('How many megabytes in a typical smartphone photo?', 'estimation', ARRAY['technology', 'facts'], 0, 1, 'published'),
  ('What share of adults meditate at least once a week?', 'estimation', ARRAY['wellness', 'habits'], 0, 2, 'published'),
  ('How many trees are on Earth (order of magnitude)?', 'estimation', ARRAY['environment', 'science'], 0, 3, 'published'),
  ('What percent of people change their mind after a structured debate?', 'estimation', ARRAY['discourse', 'psychology'], 0, 3, 'published'),
  ('How many active users does Wikipedia have per month?', 'estimation', ARRAY['internet', 'facts'], 0, 2, 'published'),
  ('What fraction of food produced globally is wasted?', 'estimation', ARRAY['environment', 'society'], 0, 2, 'published'),
  ('How many Nobel laureates are alive today?', 'estimation', ARRAY['science', 'culture'], 0, 3, 'published'),
  ('What percentage of email is spam?', 'estimation', ARRAY['internet', 'technology'], 0, 2, 'published'),
  ('How many steps does the average person take per day?', 'estimation', ARRAY['health', 'habits'], 0, 2, 'published'),
  ('What share of urban land is used for parking?', 'estimation', ARRAY['cities', 'environment'], 0, 3, 'published'),
  ('Should universities grade participation in discussions?', 'opinion', ARRAY['discourse', 'education'], 0, 2, 'published'),
  ('Is it better to be consistently moderate or occasionally extreme?', 'opinion', ARRAY['discourse', 'thinking'], 0, 2, 'published'),
  ('Would you trust an AI to mediate a disagreement between friends?', 'opinion', ARRAY['discourse', 'ai'], 0, 2, 'published'),
  ('Is anonymity net-positive for honest conversation online?', 'opinion', ARRAY['discourse', 'internet'], 0, 2, 'published'),
  ('Should prediction markets be used for public policy?', 'opinion', ARRAY['discourse', 'economics'], 0, 3, 'published'),
  ('Is it rude to ask someone why they believe something?', 'opinion', ARRAY['discourse', 'social'], 0, 1, 'published'),
  ('Do people become more polarised as they get more informed?', 'opinion', ARRAY['discourse', 'media'], 0, 2, 'published'),
  ('Should echo chambers be engineered out of social products?', 'opinion', ARRAY['discourse', 'internet'], 0, 2, 'published'),
  ('Is intellectual humility a skill that can be taught?', 'opinion', ARRAY['thinking', 'education'], 0, 2, 'published'),
  ('Would society improve if everyone answered one curiosity question daily?', 'opinion', ARRAY['meta', 'discourse'], 0, 1, 'published');
