-- Seed 100 curated questions (20 per species)
INSERT INTO public.questions (text, species, tags, upvotes, difficulty)
VALUES
  ('A farmer has 17 sheep. All but 9 run away. How many are left?', 'puzzle', ARRAY['logic', 'lateral'], 188, 1),
  ('You see a man lying dead in a field with a sealed package next to him. What happened?', 'puzzle', ARRAY['logic', 'lateral'], 53, 2),
  ('A light bulb is in a locked room with 3 switches outside. You can only enter once. How do you find the correct switch?', 'puzzle', ARRAY['logic', 'lateral'], 31, 3),
  ('What comes next: 2, 6, 12, 20, 30, ?', 'puzzle', ARRAY['logic', 'lateral'], 214, 4),
  ('A man pushes his car to a hotel and declares bankruptcy. Why?', 'puzzle', ARRAY['logic', 'lateral'], 95, 1),
  ('You have 3 boxes: apples, oranges, mixed. All labels are wrong. You pick one fruit from one box. How do you relabel all correctly?', 'puzzle', ARRAY['logic', 'lateral'], 87, 2),
  ('A woman shoots her husband, holds him underwater for 5 minutes, then hangs him. Yet he survives. Explain.', 'puzzle', ARRAY['logic', 'lateral'], 82, 3),
  ('Which weighs more: a kilogram of feathers or a kilogram of steel?', 'puzzle', ARRAY['logic', 'lateral'], 60, 4),
  ('A prisoner must choose 1 of 2 doors: one leads to freedom, one to death. Two guards, one lies always. What question do you ask?', 'puzzle', ARRAY['logic', 'lateral'], 213, 1),
  ('A sequence: 1, 11, 21, 1211, 111221, what comes next?', 'puzzle', ARRAY['logic', 'lateral'], 51, 2),
  ('You cross a river with a fox, chicken, grain. How?', 'puzzle', ARRAY['logic', 'lateral'], 198, 3),
  ('A man builds a house with all windows facing south and sees a bear. Where is he?', 'puzzle', ARRAY['logic', 'lateral'], 214, 4),
  ('What disappears as soon as you name it?', 'puzzle', ARRAY['logic', 'lateral'], 164, 1),
  ('A clock shows 3:15. What is the angle between hands?', 'puzzle', ARRAY['logic', 'lateral'], 47, 2),
  ('You throw a ball straight up. It comes back without bouncing. Why?', 'puzzle', ARRAY['logic', 'lateral'], 176, 3),
  ('A man is born in 2000 and dies in 1995. How?', 'puzzle', ARRAY['logic', 'lateral'], 133, 4),
  ('Two fathers and two sons eat three burgers each. Only 3 burgers total. How?', 'puzzle', ARRAY['logic', 'lateral'], 33, 1),
  ('You enter a room with no doors or windows. How do you get out?', 'puzzle', ARRAY['logic', 'lateral'], 32, 2),
  ('What is always in front of you but can''t be seen?', 'puzzle', ARRAY['logic', 'lateral'], 48, 3),
  ('You are in a race and pass the person in 2nd place. What position are you now?', 'puzzle', ARRAY['logic', 'lateral'], 80, 4),
  ('Should voting be mandatory in democracies?', 'opinion', ARRAY['ethics', 'society'], 84, NULL),
  ('Is it morally acceptable to lie to protect someone''s feelings?', 'opinion', ARRAY['ethics', 'society'], 154, NULL),
  ('Should billionaires exist?', 'opinion', ARRAY['ethics', 'society'], 179, NULL),
  ('Is social media doing more harm than good?', 'opinion', ARRAY['ethics', 'society'], 31, NULL),
  ('Would you erase your worst memory if you could?', 'opinion', ARRAY['ethics', 'society'], 168, NULL),
  ('Is free speech more important than preventing harm?', 'opinion', ARRAY['ethics', 'society'], 75, NULL),
  ('Should AI be allowed to make legal decisions?', 'opinion', ARRAY['ethics', 'society'], 208, NULL),
  ('Is cheating ever justified in exams if no one is harmed?', 'opinion', ARRAY['ethics', 'society'], 191, NULL),
  ('Should prisons focus on punishment or rehabilitation?', 'opinion', ARRAY['ethics', 'society'], 204, NULL),
  ('Is happiness or meaning more important in life?', 'opinion', ARRAY['ethics', 'society'], 164, NULL),
  ('Would you give up 10 years of life for perfect health?', 'opinion', ARRAY['ethics', 'society'], 132, NULL),
  ('Should we genetically enhance humans?', 'opinion', ARRAY['ethics', 'society'], 81, NULL),
  ('Is privacy more important than safety?', 'opinion', ARRAY['ethics', 'society'], 139, NULL),
  ('Should animals have legal rights similar to humans?', 'opinion', ARRAY['ethics', 'society'], 175, NULL),
  ('Is capitalism fundamentally fair?', 'opinion', ARRAY['ethics', 'society'], 96, NULL),
  ('Should parents be allowed to choose their child''s traits?', 'opinion', ARRAY['ethics', 'society'], 26, NULL),
  ('Is war ever justified?', 'opinion', ARRAY['ethics', 'society'], 219, NULL),
  ('Should people be allowed to opt out of society?', 'opinion', ARRAY['ethics', 'society'], 65, NULL),
  ('Is intelligence or kindness more important in leadership?', 'opinion', ARRAY['ethics', 'society'], 203, NULL),
  ('Would you live in a world with no religion if it reduced conflict?', 'opinion', ARRAY['ethics', 'society'], 133, NULL),
  ('Will humans land on Mars before 2040?', 'prediction', ARRAY['future', 'tech'], 112, NULL),
  ('Will AI replace most white-collar jobs by 2050?', 'prediction', ARRAY['future', 'tech'], 96, NULL),
  ('What % of jobs will be remote in 10 years?', 'prediction', ARRAY['future', 'tech'], 64, NULL),
  ('Will cash disappear in developed countries?', 'prediction', ARRAY['future', 'tech'], 80, NULL),
  ('Will there be a World War in your lifetime?', 'prediction', ARRAY['future', 'tech'], 220, NULL),
  ('What % chance do you give that AGI exists by 2035?', 'prediction', ARRAY['future', 'tech'], 111, NULL),
  ('Will brain-computer interfaces become mainstream?', 'prediction', ARRAY['future', 'tech'], 51, NULL),
  ('Will housing become more affordable in cities?', 'prediction', ARRAY['future', 'tech'], 48, NULL),
  ('Will climate change make parts of Earth uninhabitable by 2100?', 'prediction', ARRAY['future', 'tech'], 122, NULL),
  ('Will humans cure all cancers within 50 years?', 'prediction', ARRAY['future', 'tech'], 49, NULL),
  ('Will education become mostly AI-driven?', 'prediction', ARRAY['future', 'tech'], 116, NULL),
  ('What % chance do you give that we discover alien life?', 'prediction', ARRAY['future', 'tech'], 113, NULL),
  ('Will social media be regulated heavily by governments?', 'prediction', ARRAY['future', 'tech'], 179, NULL),
  ('Will there be universal basic income in major economies?', 'prediction', ARRAY['future', 'tech'], 92, NULL),
  ('Will electric planes become common?', 'prediction', ARRAY['future', 'tech'], 36, NULL),
  ('Will most people have 100+ year lifespans?', 'prediction', ARRAY['future', 'tech'], 211, NULL),
  ('Will digital currencies replace fiat money?', 'prediction', ARRAY['future', 'tech'], 142, NULL),
  ('Will war decrease globally over the next 50 years?', 'prediction', ARRAY['future', 'tech'], 162, NULL),
  ('Will meat consumption drop by 50% globally?', 'prediction', ARRAY['future', 'tech'], 56, NULL),
  ('Will humans colonise another planet?', 'prediction', ARRAY['future', 'tech'], 121, NULL),
  ('How many people are currently in the air globally?', 'estimation', ARRAY['fermi', 'numbers'], 45, 1),
  ('How many piano tuners are there in London?', 'estimation', ARRAY['fermi', 'numbers'], 166, 2),
  ('How many times does a human heart beat in a lifetime?', 'estimation', ARRAY['fermi', 'numbers'], 100, 3),
  ('How many smartphones exist worldwide right now?', 'estimation', ARRAY['fermi', 'numbers'], 185, 4),
  ('How many words does an average person speak per day?', 'estimation', ARRAY['fermi', 'numbers'], 183, 1),
  ('How many grains of sand are on Earth (order of magnitude)?', 'estimation', ARRAY['fermi', 'numbers'], 117, 2),
  ('How many people have ever lived?', 'estimation', ARRAY['fermi', 'numbers'], 172, 3),
  ('How many messages are sent on WhatsApp per day?', 'estimation', ARRAY['fermi', 'numbers'], 74, 4),
  ('How many books exist in the world today?', 'estimation', ARRAY['fermi', 'numbers'], 205, 1),
  ('How many seconds are in a lifetime?', 'estimation', ARRAY['fermi', 'numbers'], 42, 2),
  ('How many stars are visible from Earth without a telescope?', 'estimation', ARRAY['fermi', 'numbers'], 36, 3),
  ('How many bicycles exist globally?', 'estimation', ARRAY['fermi', 'numbers'], 194, 4),
  ('How many cups of coffee are consumed daily worldwide?', 'estimation', ARRAY['fermi', 'numbers'], 83, 1),
  ('How many apps are installed on an average phone?', 'estimation', ARRAY['fermi', 'numbers'], 99, 2),
  ('How many trees exist on Earth?', 'estimation', ARRAY['fermi', 'numbers'], 45, 3),
  ('How many people have ever climbed Mount Everest?', 'estimation', ARRAY['fermi', 'numbers'], 84, 4),
  ('How many languages are currently spoken?', 'estimation', ARRAY['fermi', 'numbers'], 50, 1),
  ('How many tweets are posted per day?', 'estimation', ARRAY['fermi', 'numbers'], 122, 2),
  ('How many humans have never flown in a plane?', 'estimation', ARRAY['fermi', 'numbers'], 96, 3),
  ('How many hours does humanity spend on social media per day?', 'estimation', ARRAY['fermi', 'numbers'], 141, 4),
  ('How would you redesign cities to eliminate loneliness?', 'brainstorm', ARRAY['ideas', 'design'], 187, NULL),
  ('What would education look like if grades didn''t exist?', 'brainstorm', ARRAY['ideas', 'design'], 118, NULL),
  ('How could we reduce political polarisation?', 'brainstorm', ARRAY['ideas', 'design'], 66, NULL),
  ('How would you design a fair global tax system?', 'brainstorm', ARRAY['ideas', 'design'], 119, NULL),
  ('How could we make public transport feel like a game?', 'brainstorm', ARRAY['ideas', 'design'], 115, NULL),
  ('What would a perfect news platform look like?', 'brainstorm', ARRAY['ideas', 'design'], 78, NULL),
  ('How could we make people read more books?', 'brainstorm', ARRAY['ideas', 'design'], 196, NULL),
  ('How would you fix dating apps?', 'brainstorm', ARRAY['ideas', 'design'], 93, NULL),
  ('How could we make exercise addictive?', 'brainstorm', ARRAY['ideas', 'design'], 204, NULL),
  ('What would a society without money look like?', 'brainstorm', ARRAY['ideas', 'design'], 199, NULL),
  ('How could we improve trust in science?', 'brainstorm', ARRAY['ideas', 'design'], 190, NULL),
  ('How would you redesign democracy for the internet age?', 'brainstorm', ARRAY['ideas', 'design'], 43, NULL),
  ('How could we reduce phone addiction without banning phones?', 'brainstorm', ARRAY['ideas', 'design'], 180, NULL),
  ('What would replace universities?', 'brainstorm', ARRAY['ideas', 'design'], 187, NULL),
  ('How could we make people more empathetic to strangers?', 'brainstorm', ARRAY['ideas', 'design'], 68, NULL),
  ('How would you redesign social media from scratch?', 'brainstorm', ARRAY['ideas', 'design'], 161, NULL),
  ('How could we make voting more informed?', 'brainstorm', ARRAY['ideas', 'design'], 211, NULL),
  ('What would a 4-day workweek society require?', 'brainstorm', ARRAY['ideas', 'design'], 87, NULL),
  ('How could we make climate action feel personally rewarding?', 'brainstorm', ARRAY['ideas', 'design'], 66, NULL),
  ('How would you design a system where everyone teaches and learns?', 'brainstorm', ARRAY['ideas', 'design'], 143, NULL);
