-- Seed 100 discourse-focused questions (20 per species)
INSERT INTO public.questions (text, species, tags, upvotes, difficulty)
VALUES
  ('Should governments ban TikTok over national security concerns?', 'opinion', ARRAY['discourse', 'society'], 122, NULL),
  ('Is it ethical to use AI-generated art without crediting the model?', 'opinion', ARRAY['discourse', 'society'], 78, NULL),
  ('Should Twitter/X prioritize free speech over content moderation?', 'opinion', ARRAY['discourse', 'society'], 141, NULL),
  ('Is remote work better for society than return-to-office mandates?', 'opinion', ARRAY['discourse', 'society'], 206, NULL),
  ('Should billionaires pay a wealth tax to fund public services?', 'opinion', ARRAY['discourse', 'society'], 52, NULL),
  ('Is cancel culture a real problem or a myth used to avoid accountability?', 'opinion', ARRAY['discourse', 'society'], 58, NULL),
  ('Should AI companies be required to open-source their models?', 'opinion', ARRAY['discourse', 'society'], 250, NULL),
  ('Is universal basic income a good response to automation?', 'opinion', ARRAY['discourse', 'society'], 177, NULL),
  ('Should children under 16 be banned from social media?', 'opinion', ARRAY['discourse', 'society'], 64, NULL),
  ('Is nuclear energy essential for reaching net zero?', 'opinion', ARRAY['discourse', 'society'], 133, NULL),
  ('Should police use facial recognition in public spaces?', 'opinion', ARRAY['discourse', 'society'], 189, NULL),
  ('Is the gender pay gap mostly explained by choice or discrimination?', 'opinion', ARRAY['discourse', 'society'], 54, NULL),
  ('Should universities use AI detectors on student essays?', 'opinion', ARRAY['discourse', 'society'], 272, NULL),
  ('Is cryptocurrency mostly useful or mostly speculative harm?', 'opinion', ARRAY['discourse', 'society'], 169, NULL),
  ('Should hate speech laws be expanded online?', 'opinion', ARRAY['discourse', 'society'], 94, NULL),
  ('Is the 4-day work week realistic for most industries?', 'opinion', ARRAY['discourse', 'society'], 49, NULL),
  ('Should influencers be regulated like traditional advertisers?', 'opinion', ARRAY['discourse', 'society'], 62, NULL),
  ('Is meritocracy real in modern economies?', 'opinion', ARRAY['discourse', 'society'], 151, NULL),
  ('Should gene editing in humans be allowed for disease prevention?', 'opinion', ARRAY['discourse', 'society'], 147, NULL),
  ('Is economic growth compatible with serious climate action?', 'opinion', ARRAY['discourse', 'society'], 57, NULL),
  ('Will a major country ban TikTok permanently by 2028?', 'prediction', ARRAY['discourse', 'future'], 101, NULL),
  ('What % chance do you give that AGI arrives before 2032?', 'prediction', ARRAY['discourse', 'future'], 63, NULL),
  ('Will remote work exceed 40% of knowledge jobs in 5 years?', 'prediction', ARRAY['discourse', 'future'], 181, NULL),
  ('Will Bitcoin exceed its previous all-time high again by 2027?', 'prediction', ARRAY['discourse', 'future'], 148, NULL),
  ('Will a US presidential election be significantly influenced by deepfakes?', 'prediction', ARRAY['discourse', 'future'], 55, NULL),
  ('What % chance that EU passes comprehensive AI regulation by 2026?', 'prediction', ARRAY['discourse', 'future'], 251, NULL),
  ('Will lab-grown meat capture 10% of the US market by 2035?', 'prediction', ARRAY['discourse', 'future'], 184, NULL),
  ('Will global average temperatures rise more than 1.5°C by 2030?', 'prediction', ARRAY['discourse', 'future'], 71, NULL),
  ('Will a major social platform switch to chronological feeds by default?', 'prediction', ARRAY['discourse', 'future'], 97, NULL),
  ('What % chance of a serious cyberattack on critical infrastructure this decade?', 'prediction', ARRAY['discourse', 'future'], 201, NULL),
  ('Will OpenAI remain the leading consumer AI brand in 3 years?', 'prediction', ARRAY['discourse', 'future'], 200, NULL),
  ('Will student loan forgiveness become permanent policy in the US?', 'prediction', ARRAY['discourse', 'future'], 189, NULL),
  ('What % chance that self-driving cars are common in major cities by 2035?', 'prediction', ARRAY['discourse', 'future'], 55, NULL),
  ('Will mainstream news trust scores improve or decline over 5 years?', 'prediction', ARRAY['discourse', 'future'], 187, NULL),
  ('Will a new pandemic cause comparable disruption before 2035?', 'prediction', ARRAY['discourse', 'future'], 189, NULL),
  ('What % chance that UBI is piloted nationally in a G7 country by 2030?', 'prediction', ARRAY['discourse', 'future'], 141, NULL),
  ('Will Reddit remain culturally relevant among under-25s?', 'prediction', ARRAY['discourse', 'future'], 52, NULL),
  ('Will AI replace more jobs than it creates in the next 10 years?', 'prediction', ARRAY['discourse', 'future'], 96, NULL),
  ('What % chance of a major platform exodus to decentralized social?', 'prediction', ARRAY['discourse', 'future'], 51, NULL),
  ('Will space tourism become affordable for middle-class households?', 'prediction', ARRAY['discourse', 'future'], 182, NULL),
  ('How many active ChatGPT users are there worldwide?', 'estimation', ARRAY['discourse', 'internet'], 259, 1),
  ('How many hours per day does humanity spend on TikTok?', 'estimation', ARRAY['discourse', 'internet'], 74, 2),
  ('How many political tweets are posted per day globally?', 'estimation', ARRAY['discourse', 'internet'], 114, 3),
  ('How many people work in the AI industry worldwide?', 'estimation', ARRAY['discourse', 'internet'], 147, 4),
  ('How many podcasts are published per week?', 'estimation', ARRAY['discourse', 'internet'], 76, 1),
  ('How many deepfake videos are uploaded daily (order of magnitude)?', 'estimation', ARRAY['discourse', 'internet'], 178, 2),
  ('How many Reddit posts reach the front page per day?', 'estimation', ARRAY['discourse', 'internet'], 70, 3),
  ('How many gigabytes of data does an average person generate per year?', 'estimation', ARRAY['discourse', 'internet'], 186, 4),
  ('How many news articles are published online per day?', 'estimation', ARRAY['discourse', 'internet'], 118, 1),
  ('How many people participate in online polls or surveys daily?', 'estimation', ARRAY['discourse', 'internet'], 183, 2),
  ('How many Discord servers have more than 1,000 members?', 'estimation', ARRAY['discourse', 'internet'], 248, 3),
  ('How many Wikipedia edits happen per hour?', 'estimation', ARRAY['discourse', 'internet'], 214, 4),
  ('How many phishing emails are sent per day?', 'estimation', ARRAY['discourse', 'internet'], 86, 1),
  ('How many people have deleted a social media account in the past year?', 'estimation', ARRAY['discourse', 'internet'], 66, 2),
  ('How many hours of video are uploaded to YouTube per minute?', 'estimation', ARRAY['discourse', 'internet'], 188, 3),
  ('How many climate protest participants have there been globally (lifetime)?', 'estimation', ARRAY['discourse', 'internet'], 186, 4),
  ('How many open-source GitHub repositories exist?', 'estimation', ARRAY['discourse', 'internet'], 203, 1),
  ('How many online dating matches happen per day?', 'estimation', ARRAY['discourse', 'internet'], 88, 2),
  ('How many government data requests do tech companies receive per year?', 'estimation', ARRAY['discourse', 'internet'], 135, 3),
  ('How many newsletters are sent globally each day?', 'estimation', ARRAY['discourse', 'internet'], 64, 4),
  ('How would you redesign Twitter/X to reduce outrage?', 'brainstorm', ARRAY['discourse', 'ideas'], 180, NULL),
  ('How could we make fact-checking scale on social media?', 'brainstorm', ARRAY['discourse', 'ideas'], 222, NULL),
  ('How would you fix online political polarisation?', 'brainstorm', ARRAY['discourse', 'ideas'], 56, NULL),
  ('How could AI assistants reduce rather than increase misinformation?', 'brainstorm', ARRAY['discourse', 'ideas'], 184, NULL),
  ('How would you design a fair creator economy for short-form video?', 'brainstorm', ARRAY['discourse', 'ideas'], 55, NULL),
  ('How could we make climate discourse less toxic online?', 'brainstorm', ARRAY['discourse', 'ideas'], 198, NULL),
  ('How would you rebuild trust in institutions using the internet?', 'brainstorm', ARRAY['discourse', 'ideas'], 92, NULL),
  ('How could comment sections become constructive by default?', 'brainstorm', ARRAY['discourse', 'ideas'], 167, NULL),
  ('How would you reduce doomscrolling without banning algorithms?', 'brainstorm', ARRAY['discourse', 'ideas'], 214, NULL),
  ('How could online education replace credential inflation?', 'brainstorm', ARRAY['discourse', 'ideas'], 176, NULL),
  ('How would you design a platform for productive disagreement?', 'brainstorm', ARRAY['discourse', 'ideas'], 149, NULL),
  ('How could we verify human vs bot accounts at scale?', 'brainstorm', ARRAY['discourse', 'ideas'], 238, NULL),
  ('How would you make local news financially sustainable?', 'brainstorm', ARRAY['discourse', 'ideas'], 120, NULL),
  ('How could we reduce misinformation during elections?', 'brainstorm', ARRAY['discourse', 'ideas'], 159, NULL),
  ('How would you redesign app notifications to protect attention?', 'brainstorm', ARRAY['discourse', 'ideas'], 189, NULL),
  ('How could online communities self-moderate without heavy censorship?', 'brainstorm', ARRAY['discourse', 'ideas'], 276, NULL),
  ('How would you help people escape filter bubbles voluntarily?', 'brainstorm', ARRAY['discourse', 'ideas'], 156, NULL),
  ('How could public deliberation work at internet scale?', 'brainstorm', ARRAY['discourse', 'ideas'], 132, NULL),
  ('How would you make AI transparency understandable to non-experts?', 'brainstorm', ARRAY['discourse', 'ideas'], 116, NULL),
  ('How could we reward nuanced takes over hot takes?', 'brainstorm', ARRAY['discourse', 'ideas'], 103, NULL),
  ('A viral post claims 200% of people agree. What''s wrong with that statement?', 'puzzle', ARRAY['discourse', 'logic'], 243, 1),
  ('If everyone shares a post, does reach grow linearly or exponentially?', 'puzzle', ARRAY['discourse', 'logic'], 86, 2),
  ('You see identical outrage posts from 50 accounts in 1 minute. What''s likely happening?', 'puzzle', ARRAY['discourse', 'logic'], 218, 3),
  ('A poll shows 120% approval. How many errors minimum?', 'puzzle', ARRAY['discourse', 'logic'], 239, 4),
  ('Two headlines contradict each other on the same study. What should you check first?', 'puzzle', ARRAY['discourse', 'logic'], 102, 1),
  ('A chart Y-axis starts at 95%. Why is the visual misleading?', 'puzzle', ARRAY['discourse', 'logic'], 60, 2),
  ('If a bot farm doubles daily starting with 1 bot, how many after 10 days?', 'puzzle', ARRAY['discourse', 'logic'], 187, 3),
  ('A claim spreads faster than fact-checks. Which wins short-term?', 'puzzle', ARRAY['discourse', 'logic'], 116, 4),
  ('Sample size: 12 people polled nationally. Can you generalise?', 'puzzle', ARRAY['discourse', 'logic'], 174, 1),
  ('Correlation posted online implies causation. Name one alternative explanation.', 'puzzle', ARRAY['discourse', 'logic'], 166, 2),
  ('A meme uses a 10-year-old photo as ''today''. What cognitive bias applies?', 'puzzle', ARRAY['discourse', 'logic'], 264, 3),
  ('If 70% share without reading, what % actually read (estimate logic)?', 'puzzle', ARRAY['discourse', 'logic'], 127, 4),
  ('Two groups talk past each other using the same word differently. What''s this?', 'puzzle', ARRAY['discourse', 'logic'], 226, 1),
  ('A headline says ''Scientists baffled'' but the paper doesn''t. What''s missing?', 'puzzle', ARRAY['discourse', 'logic'], 154, 2),
  ('Viral math: 0.1% of 8 billion is how many people?', 'puzzle', ARRAY['discourse', 'logic'], 113, 3),
  ('If engagement rewards outrage, what behaviour gets selected?', 'puzzle', ARRAY['discourse', 'logic'], 195, 4),
  ('A study with n=8 goes viral. What''s the minimum sensible response?', 'puzzle', ARRAY['discourse', 'logic'], 58, 1),
  ('Fake quote attributed to Einstein. What''s your first verification step?', 'puzzle', ARRAY['discourse', 'logic'], 70, 2),
  ('If echo chambers amplify beliefs, what breaks the loop?', 'puzzle', ARRAY['discourse', 'logic'], 171, 3),
  ('A poll asks ''Have you stopped beating your wife?'' Why is it invalid?', 'puzzle', ARRAY['discourse', 'logic'], 147, 4);
